# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy_api', '0001_squashed_0010_auto_20170517_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesspoint',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accesspointenvironment',
            name='root_path',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
