# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 18:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proxy_api', '0005_accesspoint_app'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesspointenvironment',
            name='root_path',
        ),
    ]
