# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 19:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proxy_api', '0007_envinterfaceparameter'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessPointEnvParamValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('access_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proxy_api.AccessPoint')),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proxy_api.EnvInterfaceParameter')),
            ],
        ),
    ]
