# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 20:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proxy_api', '0008_accesspointenvparamvalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessPointEnvCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('reg_exp', 'reg_exp'), ('jinja', 'jinja')], max_length=20)),
                ('condition', models.CharField(max_length=200)),
                ('env', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proxy_api.AccessPointEnvironment')),
            ],
        ),
        migrations.AlterField(
            model_name='accesspointenvparamvalue',
            name='access_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='param_values', to='proxy_api.AccessPoint'),
        ),
        migrations.AlterField(
            model_name='envinterfaceparameter',
            name='env',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interface_params', to='proxy_api.AccessPointEnvironment'),
        ),
    ]
