# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 21:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proxy_api', '0009_auto_20170520_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesspointenvcondition',
            name='condition',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='accesspointenvcondition',
            name='env',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='proxy_api.AccessPointEnvironment'),
        ),
    ]
