# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy_api', '0011_envvariable'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesspoint',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
