# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 00:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proxy_api', '0012_accesspoint_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesspointenvironment',
            name='value',
        ),
        migrations.AddField(
            model_name='accesspoint',
            name='response_type',
            field=models.CharField(choices=[('text', 'text'), ('json', 'json')], default='json', max_length=20),
        ),
        migrations.AlterField(
            model_name='accesspoint',
            name='path',
            field=models.CharField(default='.*', help_text='Ex: ".*"', max_length=200),
        ),
        migrations.AlterField(
            model_name='accesspointenvcondition',
            name='condition',
            field=models.TextField(help_text='{"re": "{{ env.re_msg_cond }}", "text": "{{ env.received_message }}" }'),
        ),
        migrations.AlterField(
            model_name='accesspointenvparamvalue',
            name='access_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='env_param_values', to='proxy_api.AccessPoint'),
        ),
    ]
