# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 00:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy_api', '0014_auto_20170522_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesspoint',
            name='response_type',
            field=models.CharField(choices=[('text', 'text'), ('json', 'json')], default='text', max_length=20),
        ),
    ]
