# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 22:09
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('proxy_api', '0015_auto_20170522_0009'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncommingRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root_path', models.CharField(blank=True, max_length=20, null=True)),
                ('slug', models.CharField(blank=True, max_length=20, null=True)),
                ('extra_params', jsonfield.fields.JSONField(null=True)),
                ('response_type', models.CharField(blank=True, choices=[('text', 'text'), ('json', 'json')], max_length=20, null=True)),
                ('response', models.TextField(blank=True, null=True)),
                ('payload', jsonfield.fields.JSONField(null=True)),
            ],
        ),
    ]
