# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 22:50
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('proxy_api', '0016_incommingrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='incommingrequest',
            name='request',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
