# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 23:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy_api', '0017_incommingrequest_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incommingrequest',
            name='extra_params',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
