# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 23:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proxy_api', '0018_auto_20170522_2304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incommingrequest',
            name='payload',
        ),
    ]
