# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 20:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proxy_api', '0022_auto_20170523_0047'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestReusableInterfaceParameterValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proxy_api.RequestReusableInterfaceParameter')),
                ('reusable_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='param_values', to='proxy_api.AccessPointReusableRequest')),
            ],
        ),
    ]
