# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 15:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proxy_api', '0023_requestreusableinterfaceparametervalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppVariable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('jinja', 'jinja')], max_length=20)),
                ('key', models.CharField(max_length=20)),
                ('value', models.TextField()),
                ('debug_value', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='accesspointreusablerequest',
            name='params',
        ),
        migrations.RemoveField(
            model_name='envvariable',
            name='required',
        ),
        migrations.AddField(
            model_name='envvariable',
            name='debug_value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proxyapp',
            name='debug',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='accesspointenvcondition',
            name='type',
            field=models.CharField(choices=[('reg_exp', 'reg_exp'), ('jinja', 'jinja(no implementado)')], max_length=20),
        ),
        migrations.AddField(
            model_name='appvariable',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='proxy_api.ProxyApp'),
        ),
    ]
