# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 16:18
from __future__ import unicode_literals

import apps.proxy_api.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy_api', '0024_auto_20170603_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReusableRequestPreAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('set_var', 'set_var')], max_length=20)),
                ('param1', models.TextField(blank=True, null=True)),
                ('param2', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='proxyapp',
            name='attrs',
            field=apps.proxy_api.fields.JSONTextField(blank=True, null=True),
        ),
    ]
