# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 16:20
from __future__ import unicode_literals

import apps.proxy_api.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proxy_api', '0025_auto_20170604_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proxyapp',
            name='attrs',
        ),
        migrations.AddField(
            model_name='proxyapp',
            name='attributes',
            field=apps.proxy_api.fields.JSONTextField(blank=True, null=True),
        ),
    ]
