# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 22:15
from __future__ import unicode_literals

import apps.proxy_api.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proxy_api', '0027_auto_20170604_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appvariable',
            name='app',
        ),
        migrations.AlterField(
            model_name='proxyapp',
            name='app_variables',
            field=apps.proxy_api.fields.JSONTextField(blank=True, help_text='TODO: Make key and value required', null=True),
        ),
        migrations.DeleteModel(
            name='AppVariable',
        ),
    ]
