# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 22:19
from __future__ import unicode_literals

import apps.proxy_api.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proxy_api', '0028_auto_20170604_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesspointenvironment',
            name='inteface',
            field=apps.proxy_api.fields.JSONTextField(blank=True, help_text='TODO: Make key and value required', null=True),
        ),
    ]
