# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 22:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proxy_api', '0029_accesspointenvironment_inteface'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accesspointenvironment',
            old_name='inteface',
            new_name='interface',
        ),
    ]
