# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 22:55
from __future__ import unicode_literals

import apps.proxy_api.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proxy_api', '0030_auto_20170604_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesspoint',
            name='json_env_params',
            field=apps.proxy_api.fields.JSONTextField(blank=True, help_text='TODO: Make key and value required', null=True),
        ),
    ]
