# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 00:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proxy_api', '0031_accesspoint_json_env_params'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesspointenvparamvalue',
            name='access_point',
        ),
        migrations.RemoveField(
            model_name='accesspointenvparamvalue',
            name='key',
        ),
        migrations.RemoveField(
            model_name='envinterfaceparameter',
            name='env',
        ),
        migrations.DeleteModel(
            name='AccessPointEnvParamValue',
        ),
        migrations.DeleteModel(
            name='EnvInterfaceParameter',
        ),
    ]
