# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 00:33
from __future__ import unicode_literals

import apps.proxy_api.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proxy_api', '0032_auto_20170605_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesspointenvironment',
            name='env_variables',
            field=apps.proxy_api.fields.JSONTextField(blank=True, help_text='TODO: Make key and value required', null=True),
        ),
    ]
