# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 00:51
from __future__ import unicode_literals

import apps.proxy_api.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proxy_api', '0033_accesspointenvironment_env_variables'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='envvariable',
            name='env',
        ),
        migrations.AddField(
            model_name='reusableapirequest',
            name='interface',
            field=apps.proxy_api.fields.JSONTextField(blank=True, help_text='TODO: Make key and value required', null=True),
        ),
        migrations.DeleteModel(
            name='EnvVariable',
        ),
    ]
