# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 19:41
from __future__ import unicode_literals

import apps.proxy_api.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proxy_api', '0035_accesspointreusablerequest_json_request_params'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestreusableinterfaceparameter',
            name='env',
        ),
        migrations.RemoveField(
            model_name='requestreusableinterfaceparametervalue',
            name='key',
        ),
        migrations.RemoveField(
            model_name='requestreusableinterfaceparametervalue',
            name='reusable_request',
        ),
        migrations.RemoveField(
            model_name='accesspoint',
            name='log',
        ),
        migrations.RemoveField(
            model_name='accesspointenvironment',
            name='log',
        ),
        migrations.RemoveField(
            model_name='accesspointrequestexecution',
            name='log',
        ),
        migrations.RemoveField(
            model_name='accesspointreusablerequest',
            name='log',
        ),
        migrations.RemoveField(
            model_name='incommingrequest',
            name='log',
        ),
        migrations.RemoveField(
            model_name='requeststate',
            name='log',
        ),
        migrations.RemoveField(
            model_name='reusableapirequest',
            name='log',
        ),
        migrations.RemoveField(
            model_name='reusableapirequestexecution',
            name='log',
        ),
        migrations.AlterField(
            model_name='reusableapirequest',
            name='payload',
            field=apps.proxy_api.fields.JSONTextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='RequestReusableInterfaceParameter',
        ),
        migrations.DeleteModel(
            name='RequestReusableInterfaceParameterValue',
        ),
    ]
