# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 18:57
from __future__ import unicode_literals

import apps.proxy_api.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proxy_api', '0036_auto_20170605_1941'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessPointAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('params', apps.proxy_api.fields.JSONTextField(blank=True, null=True)),
                ('access_point_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='proxy_api.AccessPointRequestExecution')),
                ('request_definition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proxy_api.ReusableApiRequest')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='ReusableRequestPreAction',
        ),
        migrations.AlterField(
            model_name='accesspoint',
            name='state_condition',
            field=models.CharField(blank=True, help_text='"aa"=="aa";\n convertir vacio en universal; state.counter >= 13 # avalidation that returns True', max_length=100, null=True),
        ),
    ]
