# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 19:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proxy_api', '0037_auto_20170607_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesspointaction',
            name='access_point_request',
        ),
        migrations.AddField(
            model_name='accesspointaction',
            name='access_point',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='proxy_api.AccessPoint'),
            preserve_default=False,
        ),
    ]
