# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy_api', '0038_auto_20170607_1903'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesspointaction',
            options={'ordering': ['access_point_order']},
        ),
        migrations.AddField(
            model_name='accesspointaction',
            name='access_point_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
