# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy_api', '0039_auto_20170607_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesspointaction',
            name='type',
            field=models.CharField(choices=[('update_var', 'update_var'), ('reusable_request', 'reusable_request')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
