# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-10 23:12
from __future__ import unicode_literals

import apps.proxy_api.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy_api', '0040_accesspointaction_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesspointreusablerequest',
            name='access_point',
        ),
        migrations.RemoveField(
            model_name='accesspointreusablerequest',
            name='request_definition',
        ),
        migrations.AddField(
            model_name='accesspointaction',
            name='post_actions',
            field=apps.proxy_api.fields.JSONTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accesspointaction',
            name='type',
            field=models.CharField(choices=[('update_state', 'update_state'), ('reusable_request', 'reusable_request')], max_length=20),
        ),
        migrations.DeleteModel(
            name='AccessPointReusableRequest',
        ),
    ]
