# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-10 23:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proxy_api', '0041_auto_20170610_2312'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookChat',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('proxy_api.accesspoint',),
        ),
    ]
